name: Deploy to AWS EC2
on:
  push:
    branches:
      - "main"


env:
  REPOSITORY: ${{github.repository}}
  REPOSITORY_NAME: ${{github.event.repository.name}}


jobs:

  deploy:
      runs-on: ubuntu-latest
      environment: docker_server
      steps:
        - name: Ejecutar comandos por SSH en EC2
          uses: appleboy/ssh-action@v1.0.0
          with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USER }}
            key: ${{ secrets.EC2_SSH_KEY }}
            port: 22
            script: |
              REPOSITORY="${{ env.REPOSITORY }}"
              REPOSITORY_NAME="${{ env.REPOSITORY_NAME }}"

              cd /home/ubuntu

              if [ ! -d "$REPOSITORY_NAME/.git" ]; then
                git clone https://github.com/$REPOSITORY.git $REPOSITORY_NAME
              else
                cd $REPOSITORY_NAME
                git pull origin main
              fi

              cd $REPOSITORY_NAME
              sudo docker compose down
              sudo docker compose up -d --build

            
              