name: Deploy to AWS EC2 with ghcr
on:
  push:
    branches:
      - "main"
env:
  REPOSITORY: ${{github.repository}}
  REPOSITORY_NAME: ${{github.event.repository.name}}


jobs:
  create-docker-image:
    runs-on: ubuntu-latest
    environment: docker_server
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Login to GCR
        uses: docker/login-action@v1
        with:
            registry: ghcr.io
            username: ${{github.actor}}
            password: ${{secrets.DEPLOY_TOKEN}}
      
      - name: Build docker imagen
        run: |
            docker build . -t ghcr.io/void1499/angular-tools:v1
            docker push ghcr.io/void1499/angular-tools:v1

            
              