name: Deploy to AWS EC2 with ghcr
on:
  push:
    branches:
      - "main"
env:
  REPOSITORY: ${{github.repository}}
  REPOSITORY_NAME: ${{github.event.repository.name}}


jobs:

 create-docker-image:
  runs-on: ubuntu-latest
  environment: docker_server
  steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Login to GHCR
      uses: docker/login-action@v1
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DEPLOY_TOKEN }}

    - name: Build and push docker image with cache
      run: |
        docker buildx build \
          --cache-from=type=local,src=/tmp/.buildx-cache \
          --cache-to=type=local,dest=/tmp/.buildx-cache-new,mode=max \
          -t ghcr.io/void1499/angular-tools:v1 \
          --push \
          .

    - name: Move new cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache

    - name: Upload docker-compose artifact
      uses: actions/upload-artifact@v4
      with:
          name: docker-compose-file
          path: docker-compose.yml

 deploy:
      needs: [create-docker-image]
      runs-on: ubuntu-latest
      environment: docker_server
      steps:
        - name: Download docker-compose artifact
          uses: actions/download-artifact@v4
          with:
           name: docker-compose-file

        - name: Show docker-compose.yml
          run: cat docker-compose.yml    

            
              